spring:
  config:
    activate:
      on-profile: prod
  test:
    enabled: false
  data:
    redis:
      url: ${vcap.services.redisbtp.credentials.uri}
      host: ${vcap.services.redisbtp.credentials.hostname}
      port: ${vcap.services.redisbtp.credentials.port:1583}
      password: ${vcap.services.redisbtp.credentials.password}
      client-type: lettuce
  jpa:
    open-in-view: false
    generate-ddl: true
    ddl-auto: update
  datasource:
    url: jdbc:postgresql://${vcap.services.postgresqlbtp.credentials.hostname}:${vcap.services.postgresqlbtp.credentials.port}/${vcap.services.postgresqlbtp.credentials.dbname}?sslmode=require
    username: ${vcap.services.postgresqlbtp.credentials.username}
    password: ${vcap.services.postgresqlbtp.credentials.password}
    hikari:
      schema: user_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS user_schema
      connection-timeout: 10000
  sql:
    init:
      mode: never
  mail:
    host: smtp.gmail.com
    port: 587
    username: final.project.petrachkou@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: ${JWT_SECRET}
    tokenExpiration: 60m
    refreshTokenExpiration: 60m
  verification:
    verificationCodeExpiration: 24h
  password:
    resetPasswordCodeExpiration: 5m
  domain: https://${APP_DOMAIN}

init:
  enabled: true

logging:
  level:
    org.springframework.data.redis: DEBUG