spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    open-in-view: false
    generate-ddl: true
    ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5433/user_db
    username: postgres
    password: postgres
    hikari:
      schema: user_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS user_schema
      connection-timeout: 10000
  sql:
    init:
      mode: never
  mail:
    host: smtp.gmail.com
    port: 587
    username: final.project.petrachkou@gmail.com
    password: nijq twbu qusy vjzd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: "someSecretKey"
    tokenExpiration: 3m
    refreshTokenExpiration: 30m
  domain: http://localhost:8080

init:
  enabled: true